import { User } from '@prisma/client'
import Layout from './components/Layout'
import LoginModal from './components/modal/LoginModal'
import RegisterModal from './components/modal/RegisterModal'
import './globals.css'
import ToasterProvider from './providers/ToasterProvider'

export const metadata = {
  title: 'twitter Clone',
  description: 'Generated by create next app',
}


interface RootLayoutProps {
  children: React.ReactNode;
  user?: User
}
const RootLayout : React.FC<RootLayoutProps> = (
  {
  children,
  user
  }) => {
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <LoginModal />
        <RegisterModal />
        <Layout user={user}>
          {children}
        </Layout>
      </body>
    </html>
  )
}

export default RootLayout;